# --------------------------------------------------------------------------------------
# SQL Script to Create and Populate the Recipe Table in the Recipes Database (RecipesDB)
# Created by Osman Balci
# Modified by Group 6 for use in HealthCoach Fitness app.
# --------------------------------------------------------------------------------------

DROP TABLE IF EXISTS PublicRecipe, UserRecipe, UserPhoto, User, UserQuestionnaire, UserWorkout, PublicWorkout;

CREATE TABLE User
(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(32) NOT NULL,
    password VARCHAR(256) NOT NULL,          /* To store Salted and Hashed Password Parts */
    first_name VARCHAR(32) NOT NULL,
    middle_name VARCHAR(32),
    last_name VARCHAR(32) NOT NULL,
    address1 VARCHAR(128) NOT NULL,
    address2 VARCHAR(128),
    city VARCHAR(64) NOT NULL,
    state VARCHAR(2) NOT NULL,
    zipcode VARCHAR(10) NOT NULL,            /* e.g., 24060-1804 */
    security_question_number INT NOT NULL,   /* Refers to the number of the selected security question */
    security_answer VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    two_factor VARCHAR(8) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE UserPhoto
(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    extension ENUM('jpeg', 'jpg', 'png', 'gif') NOT NULL,
    user_id INT UNSIGNED,
    FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE UserRecipe
(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_id INT UNSIGNED,
    name VARCHAR(256) NOT NULL,
	category VARCHAR(128) NOT NULL,
	cuisine VARCHAR(128) NOT NULL,
	website_url VARCHAR(256) NOT NULL,
	photo_url VARCHAR(256) NOT NULL,
	publisher_name VARCHAR(256) NOT NULL,
	publisher_url VARCHAR(256) NOT NULL,
	ingredients VARCHAR(768) NOT NULL,
	nutrients VARCHAR(512) NOT NULL,
    dietLabels VARCHAR(768) NOT NULL,
    healthLabels VARCHAR(768) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE
);

/* The Recipe table contains attributes of interest of a recipe. */
CREATE TABLE PublicRecipe
(
 	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(256) NOT NULL,
	category VARCHAR(128) NOT NULL,
	cuisine VARCHAR(128) NOT NULL,
	website_url VARCHAR(256) NOT NULL,
	photo_url VARCHAR(256) NOT NULL,
	publisher_name VARCHAR(256) NOT NULL,
	publisher_url VARCHAR(256) NOT NULL,
	ingredients VARCHAR(768) NOT NULL,
	nutrients VARCHAR(512) NOT NULL,
	PRIMARY KEY (id)
);


/* The UserQuestionnaire table contains the user's survey data. */
CREATE TABLE UserQuestionnaire
(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    date_entered DATE NOT NULL,    /* YYYY-MM-DD */
    questionnaire MEDIUMTEXT NOT NULL,    /* Max 16,777,215 characters for storing survey in JSON */
    user_id INT UNSIGNED,
    FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE UserWorkout
(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(256) NOT NULL,
    category VARCHAR(100),
    muscle VARCHAR(256),
    equipment VARCHAR(256),
    image_url VARCHAR(256),
    description VARCHAR(2000),
    user_id INT UNSIGNED,
    FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE PublicWorkout
(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(256) NOT NULL,
    category VARCHAR(100),
    muscle VARCHAR(256),
    equipment VARCHAR(256),
    image_url VARCHAR(256),
    description VARCHAR(2000),
    PRIMARY KEY (id)
);

/* If a value to be inserted has a single quote, e.g. Rick's, enter single quote twice as Rick''s */

INSERT INTO PublicRecipe (name, category, cuisine, website_url, photo_url, publisher_name, publisher_url, ingredients, nutrients) VALUES
('Pappardelle With Beef', 'Beef', 'Italian', 'https://www.bbcgoodfood.com/recipes/353608/', 'https://www.edamam.com/web-img/dd7/dd73b7d3c071c58ef2ea4cbad1d3f70c.jpg', 'BBC Good Food', 'https://www.bbcgoodfood.com/', '500 grams of pappardelle pasta, ½ pound of beef with red wine and carrots, 400 grams of chopped tomatoes', 'Calories: 1931.505, Total Fat: 8.6232 grams, Saturated Fat: 1.532 grams, Cholesterol: 0.0 milligrams, Sodium: 511.045 milligrams, Total Carbohydrate: 390.1519 grams, Dietary Fiber: 24.454 grams, Sugars: 24.9957 grams, Protein: 68.6436 grams'),
('Basic Brine for Seafood, Poultry, and Pork', 'Seafood', 'American', 'https://www.myrecipes.com/recipe/basic-brine-seafood-poultry-pork', 'https://www.edamam.com/web-img/80f/80fe8f0feb699f761c9a200bdefdbfbe.jpg', 'My Recipes', 'https://www.myrecipes.com/', '1 cup of kosher salt, 1 cup of light brown sugar, 2 quarts of cold water, 3 bay leaves', 'Calories: 556.634, Total Fat: 0.1504 grams, Saturated Fat: 0.041 grams, Cholesterol: 0.0 milligrams, Sodium: 4742.83016 milligrams, Total Carbohydrate: 143.57996 grams, Dietary Fiber: 0.4734 grams, Sugars: 140.679 grams, Protein: 0.31098 grams'),
('Sausage-Stuffed Squash', 'Pork', 'Mediterranean', 'https://www.delish.com/cooking/recipe-ideas/recipes/a32839/sausage-stuffed-squash-120949/', 'https://www.edamam.com/web-img/802/802a5e63e4f04b0550dc4408f8501a48.jpg', 'Delish', 'https://www.delish.com/', '6 small acorn squash, 1 roll of pork sausage, 1 chopped onion, 1 box of frozen chopped spinach, 195 grams of white rice, 1 teaspoon of poultry seasoning, 1 teaspoon of salt', 'Calories: 1683.475, Total Fat: 10.64605 grams, Saturated Fat: 2.9143 grams, Cholesterol: 17.5 milligrams, Sodium: 2801.7799 milligrams, Total Carbohydrate: 383.2784 grams, Dietary Fiber: 38.23 grams, Sugars: 8.2363 grams, Protein: 42.27425 grams'),
('Orange Glazed Duck', 'Poultry', 'Chinese', 'https://www.foodnetwork.com/recipes/sandra-lee/orange-glazed-duck-recipe-1950869', 'https://www.edamam.com/web-img/28e/28e2eab6f44ccf210c995ad2623e0099.jpeg', 'Food Network', 'https://www.foodnetwork.com/', '4 duck breasts, 1 tablespoon of salt, 1 teaspoon of ground black pepper, 1 teaspoon of poultry seasoning, ½ teaspoon of ground cumin, 1 cup of orange marmalade, ½ cup of honey, 2 tablespoons of orange liqueur', 'Calories: 2240.6995, Total Fat: 28.7461 grams, Saturated Fat: 8.89917 grams, Cholesterol: 511.28 milligrams, Sodium: 2774.6464 milligrams, Total Carbohydrate: 365.9528 grams, Dietary Fiber: 3.4406 grams, Sugars: 342.4643 grams, Protein: 133.877 grams'),
('Cauliflower Mash', 'Vegetarian', 'Greek', 'https://www.thedailymeal.com/recipes/healthy-cauliflower-mash-recipe', 'https://www.edamam.com/web-img/d55/d5567e6015f45169673767422528204f.jpg', 'The Daily Meal', 'https://www.thedailymeal.com/', '1 pound of frozen or fresh cauliflower, ¼ cup of fat-free soy milk, 1 clove garlic chopped, ½ teaspoon of Italian seasoning, 1 teaspoon of poultry seasoning, 1 teaspoon of nutritional yeast, 2 tablespoons of cornstarch, 2 tablespoons of water to mix with corn starch, 1 tablespoon of fresh parsley', 'Calories: 294.839, Total Fat: 2.7033 grams, Saturated Fat: 0.78777 grams, Cholesterol: 0.0 milligrams, Sodium: 174.9012 milligrams, Total Carbohydrate: 59.7439 grams, Dietary Fiber: 11.5922 grams, Sugars: 11.5033 grams, Protein: 13.9217 grams'),
('Gremolata', 'Vegetarian', 'French', 'https://www.epicurious.com/recipes/food/views/gremolata-104971', 'https://www.edamam.com/web-img/f70/f70c395b990a25b7db1654ce08e335cb.jpg', 'Epicurious', 'https://www.epicurious.com/', '1 lemon, ¼ cup of finely chopped fresh parsley, 3 garlic cloves finely chopped', 'Calories: 35.6299, Total Fat: 0.3374 grams, Saturated Fat: 0.05043 grams, Cholesterol: 0.0 milligrams, Sodium: 11.09 milligrams, Total Carbohydrate: 9.3305 grams, Dietary Fiber: 2.308 grams, Sugars: 1.6675 grams, Protein: 1.6559 grams'),
('Vegetarian Chili', 'Vegetarian', 'Mexican', 'https://www.seriouseats.com/recipes/2010/02/dinner-tonight-vegetarian-chili-recipe.html', 'https://www.edamam.com/web-img/f0c/f0c378fcf68cbcab4e9778a77a935daa.jpg', 'Serious Eats', 'https://www.seriouseats.com/', '2 teaspoons of olive oil, 2 carrots peeled and cut into thin rounds, 1 leek whites cut into thin rounds, 1 red bell pepper stemmed seeded and flesh cut into medium dice, 2 ribs celery cut into thin slices, 1 teaspoon of fine salt, 28 ounces of can whole peeled tomatoes, 1 quart of cold water, 15 ounces of can red kidney beans, 4 teaspoons of chili powder or to taste, 2 cups of cooked rice', 'Calories: 1329.12299, Total Fat: 18.9293 grams, Saturated Fat: 2.9379 grams, Cholesterol: 0.0 milligrams, Sodium: 4742.2157 milligrams, Total Carbohydrate: 247.1466 grams, Dietary Fiber: 52.2897 grams, Sugars: 52.6591 grams, Protein: 54.359 grams'),
('Spring Vegetable Tagliatelle with Lemon and Chive Sauce', 'Vegetarian', 'Greek', 'https://www.bbcgoodfood.com/recipes/460647/', 'https://www.edamam.com/web-img/c4b/c4b0f6afe95b6b4f4148727b93d4a23e.jpg', 'BBC Good Food', 'https://www.bbcgoodfood.com/', '450 grams of mixed spring vegetables such as green beans, asparagus, broad beans and peas, 1 tablespoon of Dijon mustard, 400 grams of tagliatelle, 1 tablespoon of olive oil, 1 lemon, 3 tablespoons of snipped chives', 'Calories: 1996.36, Total Fat: 22.0807 grams, Saturated Fat: 3.35944 grams, Cholesterol: 0.0 milligrams, Sodium: 213.8 milligrams, Total Carbohydrate: 370.3766 grams, Dietary Fiber: 38.199 grams, Sugars: 37.9495 grams, Protein: 78.0433 grams'),
('Spanish Seafood Rice', 'Seafood', 'Mexican', 'https://www.bbcgoodfood.com/recipes/412624/', 'https://www.edamam.com/web-img/5be/5be59ff9c94bdc3d3ad0fa40fa5f4b5c.jpg', 'BBC Good Food', 'https://www.bbcgoodfood.com/', '1 onion finely chopped, 250 grams of paella rice, 850 ml of hot vegetable stock, 2 garlic cloves sliced, 1 small handful flat-leaf parsley roughly chopped, ½ small lemon juice, 1 tablespoon of olive oil, 1 each of red and yellow peppers deseeded and sliced', 'Calories: 1146.8495, Total Fat: 15.9594 grams, Saturated Fat: 2.4434 grams, Cholesterol: 0.0 milligrams, Sodium: 148.4225 milligrams, Total Carbohydrate: 227.7574 grams, Dietary Fiber: 5.2515 grams, Sugars: 6.4355 grams, Protein: 20.9674 grams'),
('Favorite Festival Steamed Crabs', 'Seafood', 'Mediterranean', 'https://food52.com/recipes/13839-favorite-festival-steamed-crabs', 'https://www.edamam.com/web-img/b88/b8845de02979610a39b2f1433476d30f.jpg', 'Food52', 'https://food52.com/', '1 dozen of live blue crabs, 5 tablespoons of phillips seafood seasoning, 32 ounces of beer', 'Calories: 676.8694, Total Fat: 4.3782 grams, Saturated Fat: 1.28324 grams, Cholesterol: 196.56 milligrams, Sodium: 780.5873 milligrams, Total Carbohydrate: 46.73565 grams, Dietary Fiber: 2.486 grams, Sugars: 0.396 grams, Protein: 51.794 grams'),
('Florentine Pizza', 'Pizza', 'Italian', 'https://www.bbcgoodfood.com/recipes/3265/', 'https://www.edamam.com/web-img/5d2/5d2071711a8596f95dce3c5486a630e5.jpg', 'BBC Good Food', 'https://www.bbcgoodfood.com/', '290 grams of antipasti mushrooms, 175 grams of washed spinach leaves, 6 tablespoons of tomato sauce, 4 medium eggs, 12 inches of bought pizza base, 50 grams of parmesan finely grated', 'Calories: 1905.3399, Total Fat: 270.0719 grams, Saturated Fat: 72.3456 grams, Cholesterol: 688.72 milligrams, Sodium: 4344.7574 milligrams, Total Carbohydrate: 3434.695 grams, Dietary Fiber: 190.088 grams, Sugars: 62.18534 grams, Protein: 648.5642 grams'),
('Pizza Margherita', 'Pizza', 'Mediterranean', 'https://www.saveur.com/article/Recipes/Saveur-100-2011-Pizza-Margherita', 'https://www.edamam.com/web-img/2d5/2d540d2225762b0f6579bf8757cab142.jpg', 'Saveur', 'https://www.saveur.com/', '1½ teaspoons of active dry yeast, 7 cups of flour, preferably Caputo brand, plus more, 4 teaspoons of sugar, 4½ teaspoons of kosher salt, plus more to taste, 1 teaspoon of extra-virgin olive oil, 28 ounces of can whole peeled San Marzano tomatoes, 8 ounces of mozzarella fior di latte ovoline or mozzarella di buffala, thinly sliced and patted dry with paper towels, 16 basil leaves torn by hand', 'Calories: 4134.4061, Total Fat: 65.8593 grams, Saturated Fat: 32.0914 grams, Cholesterol: 179.1689 milligrams, Sodium: 4490.2294 milligrams, Total Carbohydrate: 723.0394 grams, Dietary Fiber: 34.8924 grams, Sugars: 42.3654 grams, Protein: 150.3319 grams'),
('Rick''s Mango, Jicama, and Cucumber Salads', 'Salads', 'American', 'https://www.marthastewart.com/318354/ricks-mango-jicama-and-cucumber-salads', 'https://www.edamam.com/web-img/3fe/3fe43c052f0425849211ce583ffbd77e.jpg', 'Martha Stewart', 'https://www.marthastewart.com/', '2 medium mangos, about 1½ pounds total, peeled, flesh cut from pits, and sliced into ½-inch-wide fingers or wedges, 1 medium jicama, about 1 pound, peeled and cut into long ½-inch-wide fingers or wedges, 1 english cucumber, or 2 regular cucumbers, cut into long ½-inch-wide fingers or wedges, 1 teaspoon of pure ground chile (guajillo or ancho, or substitute a little cayenne), ½ teaspoon of coarse salt, 2 limes, each cut into 6 wedges', 'Calories: 535.0214, Total Fat: 2.824 grams, Saturated Fat: 0.6742 grams, Cholesterol: 0.0 milligrams, Sodium: 971.193 milligrams, Total Carbohydrate: 134.4962 grams, Dietary Fiber: 33.4810 grams, Sugars: 80.9565 grams, Protein: 9.91875 grams'),
('Cucumber Salad', 'Salads', 'Turkish', 'https://www.saveur.com/article/Recipes/Cucumber-Salad', 'https://www.edamam.com/web-img/593/5933f1f1b4a2a5e2f3a8cfb0b34bb92b.jpg', 'Saveur', 'https://www.saveur.com/', '1 cup of apple cider vinegar, ½ cup of sugar, 1½ teaspoons of kosher salt, plus more to taste, 2 English seedless cucumbers, 4 shallots thinly-sliced crosswise, 1 Freshly ground black pepper or more to taste', 'Calories: 706.6509, Total Fat: 1.0145 grams, Saturated Fat: 0.3124 grams, Cholesterol: 0.0 milligrams, Sodium: 2746.3886 milligrams, Total Carbohydrate: 166.0508 grams, Dietary Fiber: 11.4754 grams, Sugars: 129.44032 grams, Protein: 10.19339 grams'),
('Turkish Coffee', 'Beverages', 'Turkish', 'https://food52.com/recipes/40287-turkish-coffee', 'https://www.edamam.com/web-img/8bc/8bc6df7902e4d7bcc1d1650f3b32351e.jpg', 'Food52', 'https://food52.com/', '3 cups of (Turkish coffee cup-sized cups) of cold filtered water, 2½ tablespoons of ground Turkish coffee, 9 grams of sugar', 'Calories: 35.1071, Total Fat: 0.00739 grams, Saturated Fat: 7.3999 grams, Cholesterol: 0.0 milligrams, Sodium: 15.0497 milligrams, Total Carbohydrate: 8.9742 grams, Dietary Fiber: 0.0 grams, Sugars: 8.958 grams, Protein: 0.04439 grams'),
('Pistachio and Orange Blossom Turkish Delight', 'Desserts', 'Turkish', 'https://food52.com/recipes/30715-pistachio-and-orange-blossom-turkish-delight', 'https://www.edamam.com/web-img/98a/98a7f8838888e6814007167f6acc60fc.jpg', 'Food52', 'https://food52.com/', '400 grams of sugar, 500 milliliters of water, 100 grams of cornstarch, ½ teaspoon of baking powder, 1 teaspoon of orange blossom water, ¼ teaspoon of cinnamon, 25 grams of pistachios, 50 grams of powdered sugar', 'Calories: 2266.7785, Total Fat: 11.40556 grams, Saturated Fat: 1.4002 grams, Cholesterol: 0.0 milligrams, Sodium: 216.0511 milligrams, Total Carbohydrate: 549.03063 grams, Dietary Fiber: 3.82475 grams, Sugars: 450.0341 grams, Protein: 5.355735 grams'),
('Ice Cream Bombe', 'Desserts', 'French', 'https://www.marthastewart.com/316880/ice-cream-bombe', 'https://www.edamam.com/web-img/fd0/fd05892aae3b086f0f315e99d629c3d7.jpg', 'Martha Stewart', 'https://www.marthastewart.com/', '2 pints of black currant sorbet, 1 raspberry sorbet, 1 pint of Vanilla Ice Cream', 'Calories: 1765.48, Total Fat: 29.04 grams, Saturated Fat: 17.9256 grams, Cholesterol: 116.16 milligrams, Sodium: 264.2 milligrams, Total Carbohydrate: 378.184 grams, Dietary Fiber: 12.448 grams, Sugars: 361.3008 grams, Protein: 9.24 grams'),
('Buttermilk and Lekvar Ice Cream', 'Desserts', 'American', 'https://www.seriouseats.com/recipes/2012/04/buttermilk-levkar-ice-cream-recipe.html', 'https://www.edamam.com/web-img/e14/e143d6f404cb33ee31b511562e3f6025.jpg', 'Serious Eats', 'https://www.seriouseats.com/', '3 cups of buttermilk, 12 ounces of can or jar of lekvar (jewish-style prune paste), 1 tablespoon of juice from 1 lemon, 2 tablespoons of dark molasses, 3 tablespoons of light brown or white sugar', 'Calories: 917.3324, Total Fat: 7.2281 grams, Saturated Fat: 4.0945 grams, Cholesterol: 29.4 milligrams, Sodium: 1422.1488 milligrams, Total Carbohydrate: 198.6998 grams, Dietary Fiber: 13.2983 grams, Sugars: 103.15014 grams, Protein: 27.4339 grams'),
('Rustic Bread', 'Bread', 'Middle Eastern', 'https://www.goodhousekeeping.com/food-recipes/a10951/rustic-bread-recipe-clv0511/', 'https://www.edamam.com/web-img/f7d/f7dee0a2eada97a20478d13722ccc9c0.jpg', 'Good Housekeeping', 'https://www.goodhousekeeping.com/', '0.67 cup of whole milk, 1 tablespoon of superfine sugar, 1 ounce of fresh active yeast, 5 cups of bread flour, 2 sprig fresh rosemary', 'Calories: 2735.8587, Total Fat: 19.4274 grams, Saturated Fat: 5.2878 grams, Cholesterol: 6.348 milligrams, Sodium: 101.20465 milligrams, Total Carbohydrate: 533.4302 grams, Dietary Fiber: 25.47602 grams, Sugars: 25.34924 grams, Protein: 99.00816 grams'),
('Pita Bread', 'Bread', 'Middle Eastern', 'https://www.foodnetwork.com/recipes/tyler-florence/pita-bread-recipe-1914218', 'https://www.edamam.com/web-img/993/99337b8d4bc84f381f57ddd300dafdca.jpeg', 'Food Network', 'https://www.foodnetwork.com/', '1 package of active dry yeast, 1 teaspoon of sugar, 1½ cups of warm water, 1 teaspoon of salt, 3½ cups of bread flour, plus more for dusting, 1 teaspoon of olive oil', 'Calories: 7838.869, Total Fat: 42.4897 grams, Saturated Fat: 6.16306 grams, Cholesterol: 0.0 milligrams, Sodium: 2438.582 milligrams, Total Carbohydrate: 1559.21291 grams, Dietary Fiber: 60.64799 grams, Sugars: 10.77445 grams, Protein: 268.95369 grams'),
('French Bread', 'Bread', 'French', 'https://www.delish.com/cooking/recipe-ideas/recipes/a27625/french-bread-3332/', 'https://www.edamam.com/web-img/2ed/2ed5d99530511262c244d5153a3876fc.jpg', 'Delish', 'https://www.delish.com/', '3 cups of bread flour, 2½ teaspoons of instant active dry yeast, 1 teaspoon of salt, 1 cup of spring water, 1 tablespoon of vegetable oil, 1 egg white, 1 tablespoon of whole milk', 'Calories: 1662.848, Total Fat: 22.11598 grams, Saturated Fat: 2.29423 grams, Cholesterol: 1.5 milligrams, Sodium: 1658.997432 milligrams, Total Carbohydrate: 303.13302 grams, Dietary Fiber: 12.554 grams, Sugars: 2.21904 grams, Protein: 56.6319 grams'),
('Chicken and Rice Soup', 'Soups', 'American', 'https://www.epicurious.com/recipes/food/views/chicken-rice-soup-366990', 'https://www.edamam.com/web-img/abe/abe60dc78fb74335135da20aa9f2b01b.jpg', 'Epicurious', 'https://www.epicurious.com/', '4 cups of low-sodium chicken broth, ⅓ cup of long-grain white rice, 2 skinless boneless chicken breast halves, 1 carrot peeled and diced, 1 cup of frozen peas, 1 garlic clove sliced, 1 teaspoon of minced fresh parsley', 'Calories: 2039.269, Total Fat: 22.749 grams, Saturated Fat: 5.476 grams, Cholesterol: 397.12 milligrams, Sodium: 4777.378 milligrams, Total Carbohydrate: 279.146 grams, Dietary Fiber: 10.456 grams, Sugars: 11.832 grams, Protein: 170.392 grams'),
('Balsamic Blueberries with Vanilla Ice Cream', 'Desserts', 'French', 'http://www.bbcgoodfood.com/recipes/11024/', 'https://www.edamam.com/web-img/b4b/b4b0577c260b0f071b5d286c7b2a47d5.jpg', 'BBC Good Food', 'http://www.bbcgoodfood.com/', '4 scoops of good-quality vanilla ice cream, 4 crisp biscuits, 1 tablespoon of caster sugar, 1 teaspoon of balsamic vinegar, 125 grams of blueberries', 'Calories: 133.964, Total Fat: 0.4125 grams, Saturated Fat: 0.035 grams, Cholesterol: 0.0 milligrams, Sodium: 2.619 milligrams, Total Carbohydrate: 34.012 grams, Dietary Fiber: 3.0 grams, Sugars: 28.212 grams, Protein: 0.951 grams'),
('Baklava Rolls', 'Desserts', 'Middle Eastern', 'https://www.mamaslebanesekitchen.com/desserts/lebanese-baklava-recipe/', 'https://www.edamam.com/web-img/b6f/b6fcf73b8a5e016aa0e56b20f4df266d.jpg', 'Mama''s Lebanese Kitchen', 'https://www.mamaslebanesekitchen.com', '1 cup of sugar, ¾ cup of water, ½ teaspoon of lemon juice, 1 teaspoon of orange blossom water, 1 pack of Fillo Dough, thawed, 1 cup of coarsely grinded walnuts, ⅓ cup of finely grinded pistachio, ⅓ pound of sweet/unsalted butter melted', 'Calories: 774.559, Total Fat: 0.0061 grams, Saturated Fat: 0.001 grams, Cholesterol: 0.0 milligrams, Sodium: 9.332 milligrams, Total Carbohydrate: 200.135 grams, Dietary Fiber: 0.0076 grams, Sugars: 199.664 grams, Protein: 0.00889 grams'),
('Tropical Breakfast Parfait', 'Breakfast', 'Tropical', 'https://www.foodnetwork.com/recipes/rachael-ray/tropical-breakfast-parfait-recipe-1957021', 'https://www.edamam.com/web-img/b07/b072b5e540fe302ead7a4ac06e6435f2.jpeg', 'Food Network', 'https://www.foodnetwork.com/', '2 cups of vanilla yogurt, 1 small can of mandarin oranges, drained, ¾ cup of crisped rice breakfast cereal, 1 cup of diced fresh pineapple', 'Calories: 675.7838, Total Fat: 7.1803 grams, Saturated Fat: 4.1138 grams, Cholesterol: 24.5 milligrams, Sodium: 436.0772 milligrams, Total Carbohydrate: 132.4808 grams, Dietary Fiber: 8.447 grams, Sugars: 98.1727 grams, Protein: 29.9434 grams'),
('Aloha Punch', 'Beverages', 'Tropical', 'https://www.myrecipes.com/recipe/aloha-punch', 'https://www.edamam.com/web-img/fc2/fc23ac49b367454e4e397de18341468c.jpg', 'My Recipes', 'https://www.myrecipes.com/', '2 cups of pineapple juice, 1 cup of strawberry juice, 1 cup of guava juice, 1 cup of pear nectar, 1 cup of orange carbonated beverage', 'Calories: 621.77, Total Fat: 1.2316 grams, Saturated Fat: 0.1155 grams, Cholesterol: 0.0 milligrams, Sodium: 86.308 milligrams, Total Carbohydrate: 156.2111 grams, Dietary Fiber: 8.05 grams, Sugars: 127.7373 grams, Protein: 3.3193 grams'),
('Asian Shrimp Salad', 'Salads', 'Asian', 'https://www.delish.com/cooking/recipe-ideas/recipes/a33207/asian-shrimp-salad-121154/', 'https://www.edamam.com/web-img/f78/f78d4e1c40ddd80ee943cce6b53374b8.jpg', 'Delish', 'https://www.delish.com/', '1 pound of peeled raw jumbo shrimp, 2 medium of summer squash, 1 bag of Asian Supreme Complete Salad with Sesame Orange Dressing', 'Calories: 446.34058, Total Fat: 5.444 grams, Saturated Fat: 1.376 grams, Cholesterol: 571.5263 milligrams, Sodium: 2575.1728 milligrams, Total Carbohydrate: 32.65219 grams, Dietary Fiber: 7.456 grams, Sugars: 20.8725 grams, Protein: 67.7085 grams'),
('Isan Grilled Beef Salad', 'Salads', 'Italian', 'https://www.seriouseats.com/recipes/2012/03/isan-thai-grilled-beef-salad-recipe.html', 'https://www.edamam.com/web-img/2ff/2ff49951a2c13a3d7d908013609b77d4.jpg', 'Serious Eats', 'https://www.seriouseats.com/', '3 tablespoons of lime juice, 3 tablespoons of fish sauce, 1 pinch of sugar, 1 teaspoon of chile powder, 6 ounces of beef tenderloin, 2 shallots sliced finely lengthwise, 1 spring onion sliced finely in rings, 1 handful of mint leaves', 'Calories: 2169.6761, Total Fat: 32.7841 grams, Saturated Fat: 12.7375 grams, Cholesterol: 140.245 milligrams, Sodium: 3718.3253 milligrams, Total Carbohydrate: 388.9315 grams, Dietary Fiber: 6.0727 grams, Sugars: 0.2599 grams, Protein: 69.1238 grams'),
('Vietnamese Beef Soup', 'Soups', 'Vietnamese', 'https://www.goodhousekeeping.com/food-recipes/a11448/vietnamese-beef-soup-121358/', 'https://www.edamam.com/web-img/f75/f75be213fc90853a98d91ab01872e5cf.jpg', 'Good Housekeeping', 'https://www.goodhousekeeping.com', '4 cans of low-sodium beef broth, 6 ounces of rice noodles, 1 package of baby spinach, 1 fresh basil leaves, 8 ounces of thinly sliced deli roast beef, 1 scallion', 'Calories: 1077.40919, Total Fat: 14.439 grams, Saturated Fat: 5.3569 grams, Cholesterol: 115.666 milligrams, Sodium: 8944.6682 milligrams, Total Carbohydrate: 150.57758 grams, Dietary Fiber: 9.74355 grams, Sugars: 2.4761 grams, Protein: 81.3391 grams'),
('Mexican Pumpkin Punch', 'Beverages', 'Mexican', 'https://www.foodnetwork.com/recipes/food-network-kitchen/mexican-pumpkin-punch-recipe-1973611', 'https://www.edamam.com/web-img/601/601b146a6025112aba4d33f38d0553f5.jpeg', 'Food Network', 'https://www.foodnetwork.com', '2 cups of packed dark brown sugar, 4 cinnamon sticks preferably Mexican, 1 can of pure pumpkin, 2 limes', 'Calories: 1843.448, Total Fat: 0.80296 grams, Saturated Fat: 0.27648 grams, Cholesterol: 0.0 milligrams, Sodium: 130.98 milligrams, Total Carbohydrate: 480.49096 grams, Dietary Fiber: 11.3044 grams, Sugars: 440.58388 grams, Protein: 5.94096 grams');

INSERT INTO PublicWorkout (name, category, muscle, equipment, image_url, description) VALUES
('Biceps Curls With Barbell', 'Arms', 'Biceps brachii, Brachialis', 'Barbell', 'https://wger.de/media/exercise-images/74/Bicep-curls-1.png', 'Hold the Barbell shoulder-wide, the back is straight, the shoulders slightly back, the arms are streched. Bend the arms, bringing the weight up, with a fast movement. Without pausing, let down the bar with a slow and controlled movement.\nDon''t allow your body to swing during the exercise, all work is done by the biceps, which are the only mucles that should move (pay attention to the elbows).'),
('Bent Over Rowing Reverse', 'Back', 'Anterior deltoid, Biceps brachii', 'Barbell', 'https://wger.de/media/exercise-images/110/Reverse-grip-bent-over-rows-1.png', 'The same as regular rowing, but holding a reversed grip (your palms pointing forwards):\nGrab the barbell with a wide grip (slightly more than shoulder wide) and lean forward. Your upper body is not quite parallel to the floor, but forms a slight angle. The chest''s out during the whole exercise.\nPull now the barbell with a fast movement towards your belly button, not further up. Go slowly down to the initial position. Don''t swing with your body and keep your arms next to your body.'),
('Bent Over Rowing', 'Back', 'Latissimus dorsi, Anterior deltoid, Biceps brachii', 'Barbell', 'https://wger.de/media/exercise-images/109/Barbell-rear-delt-row-1.png', 'Grab the barbell with a wide grip (slightly more than shoulder wide) and lean forward. Your upper body is not quite parallel to the floor, but forms a slight angle. The chest''s out during the whole exercise.\nPull now the barbell with a fast movement towards your belly button, not further up. Go slowly down to the initial position. Don''t swing with your body and keep your arms next to your body.'),
('Bench Press Narrow Grip', 'Arms', 'Triceps brachii, Anterior deltoid, Pectoralis major', 'Barbell', 'https://wger.de/media/exercise-images/88/Narrow-grip-bench-press-1.png', ''),
('Benchpress Dumbbells', 'Chest', 'Pectoralis major, Anterior deltoid, Triceps brachii', 'Bench, Dumbbell', 'https://wger.de/media/exercise-images/97/Dumbbell-bench-press-1.png', ''),
('Bench Press', 'Chest', 'Pectoralis major, Anterior deltoid, Triceps brachii', 'Barbell, Bench', 'https://wger.de/media/exercise-images/192/Bench-press-1.png', 'Lay down on a bench, the bar should be directly above your eyes, the knees are somewhat angled and the feet are firmly on the floor. Concentrate, breath deeply and grab the bar more than shoulder wide. Bring it slowly down till it briefly touches your chest at the height of your nipples. Push the bar up.\nIf you train with a high weight it is advisable to have a spotter that can help you up if you can''t lift the weight on your own.\nWith the width of the grip you can also control which part of the chest is trained more:\n'),
('Biceps Curl With Cable', 'Arms', 'Biceps brachii', '', 'https://wger.de/media/exercise-images/129/Standing-biceps-curl-1.png', 'Stand around 30 - 40cm away from the cable, the feet are firmly on the floor. Take the bar and lift the weight with a fast movements. Lower the weight as with the dumbbell curls slowly and controlled.'),
('Butterfly', 'Chest', 'Pectoralis major, Anterior deltoid', '', 'https://wger.de/media/exercise-images/98/Butterfly-machine-2.png', 'Sit on the butterfly machine, the feet have a good contact with the floor, the upper arms are parallel to the floor. Press your arms together till the handles are practically together (but aren''t!). Go slowly back. The weights should stay all the time in the air.'),
('Chin-ups', 'Back', 'Biceps brachii, Latissimus dorsi', 'Pull-up bar', 'https://wger.de/media/exercise-images/181/Chin-ups-2.png', 'Like pull-ups but with a reverse grip'),
('Dips', 'Arms', 'Triceps brachii, Pectoralis major, Rectus abdominis', '', 'https://wger.de/media/exercise-images/82/Tricep-dips-2-1.png', 'Hold onto the bars at a narrow place (if they are not parallel) and press yourself up, but don''t stretch the arms completely, so the muscles stay during the whole exercise under tension. Now bend the arms and go down as much as you can, keeping the elbows always pointing back, At this point, you can make a short pause before repeating the movement.'),
('Crunches', 'Abs', 'Rectus abdominis, Serratus anterior', 'Bench, Gym Mat', 'https://wger.de/media/exercise-images/91/Crunches-1.png', 'Lay down on your back a soft surface, the feet are on the floor. Ask a partner or use some other help (barbell, etc.) to keep them fixed, your hands are behind your head. From this position move your upper body up till your head or elbows touch your knees. Do this movement by rolling up your back.'),
('Decline Bench Press Barbell', 'Chest', 'Pectoralis major', 'Barbell', 'https://wger.de/media/exercise-images/100/Decline-bench-press-1.png', 'Lay down on a decline bench, the bar should be directly above your eyes, the knees are somewhat angled and the feet are firmly on the floor. Concentrate, breath deeply and grab the bar more than shoulder wide. Bring it slowly down till it briefly touches your chest at the height of your nipples. Push the bar up.'),
('Dips Between Two Benches', 'Arms', 'Triceps brachii', 'Bench', 'https://wger.de/media/exercise-images/83/Bench-dips-1.png', 'Put two benches so far appart, that you can hold onto one with your hands and are just able to reach the other with your feet. The legs stay during the exercise completely stretched. With your elbows facing back, bend them as much as you can. Push yourself up, but don''t stretch out the arms.'),
('Dumbbell Lunges Walking', 'Legs', 'Quadriceps femoris, Gluteus maximus', 'Dumbbell', 'https://wger.de/media/exercise-images/113/Walking-lunges-1.png', 'Take two dumbbells in your hands, stand straight, feet about shoulder wide. Take one long step so that the front knee is approximately forming a right angle. The back leg is streched, the knee is low but doesn''t touch the ground. \"Complete\" the step by standing up and repeat the movement with the other leg.'),
('French Press (skullcrusher) SZ-bar', 'Arms', 'Triceps brachii', 'Bench, SZ-Bar', 'https://wger.de/media/exercise-images/84/Lying-close-grip-triceps-press-to-chin-1.png', 'Hold the SZ-bar and lay down on a flat bench in such a way that around 1/4 of your head is over the edge. Stretch your arms with the bar and bend them so that the bar is lowered. Just before it touches your forehead, push it up.'),
('Front Squats', 'Legs', 'Gluteus maximus, Rectus abdominis', 'Barbell', 'https://wger.de/media/exercise-images/191/Front-squat-1-857x1024.png', ''),
('Good Mornings', 'Legs', 'Biceps femoris', '', 'https://wger.de/media/exercise-images/116/Good-mornings-2.png', ''),
('Hammercurls', 'Arms', 'Biceps brachii', 'Dumbbell', 'https://wger.de/media/exercise-images/86/Bicep-hammer-curl-1.png', 'Hold two dumbbells and sit on a bench with a straight back, the shoulders are slightly rolled backwards. Your pals point to your body. Bend the arms and bring the weight up with a fast movement. Don''t rotate your hands, as with the curls. Without any pause bring the dumbbell down with a slow, controlled movement.'),
('Hammercurls on Cable', 'Arms', 'Biceps brachii, Brachialis', '', 'https://wger.de/media/exercise-images/138/Hammer-curls-with-rope-1.png', 'Take a cable in your hands (palms parallel, point to each other), the body is straight. Bend the arms and bring the weight up with a fast movement. Without any pause bring it back down with a slow, controlled movement, but don''t stretch completely your arms.'),
('Hyperextensions', 'Back', 'Trapezius', '', 'https://wger.de/media/exercise-images/128/Hyperextensions-1.png', 'Lay on the hyperextension pad with the belly button just at the leading edge, the upper body can hang freely. Tense your whole back''s muscles and bring your upper body up till it is horizontal, but not more. Go slowly down and don''t relax your muscles.'),
('Incline Bench Press', 'Chest', 'Pectoralis major, Triceps brachii', 'Barbell, Incline bench', 'https://wger.de/media/exercise-images/163/Incline-bench-press-1.png', ''),
('Lateral Raises', 'Shoulders', 'Anterior deltoid', 'Dumbbell', 'https://wger.de/media/exercise-images/148/lateral-dumbbell-raises-large-2.png', ''),
('Leg Curls (laying)', 'Legs', 'Biceps femoris', '', 'https://wger.de/media/exercise-images/154/lying-leg-curl-machine-large-1.png', 'Lay on a bench and put your calves behind the leg holder (better if they are hold on around the lower calves). Hold a grip on the bars to make sure the body is firmly in place. Bend your legs bringing the weight up, go slowly back. During the exercise the body should not move, all work is done by the legs.'),
('Leg Curls (sitting)', 'Legs', 'Biceps femoris', '', 'https://wger.de/media/exercise-images/117/seated-leg-curl-large-1.png', ''),
('Leg Curls (standing)', 'Legs', 'Biceps femoris', '', 'https://wger.de/media/exercise-images/118/standing-leg-curls-large-1.png', ''),
('Leg Extension', 'Legs', 'Quadriceps femoris', '', 'https://wger.de/media/exercise-images/177/Seated-leg-curl-1.png', 'Seated Leg Extension Machine'),
('Leg Press on Hackenschmidt Machine', 'Legs', 'Quadriceps femoris', '', 'https://wger.de/media/exercise-images/130/Narrow-stance-hack-squats-1-1024x721.png', ''),
('Leg Raises, Lying', 'Abs', 'Rectus abdominis, Serratus anterior', 'Gym mat', 'https://wger.de/media/exercise-images/125/Leg-raises-2.png', 'Lay down on a bench and hold onto the recliner with your hands to keep you stable. Hold your legs straight and lift them till they make an angle of about 45°. Make a short pause of 1 sec. and go slowly down to the initial position. To increase the intensity you can make a longer pause of 7 sec. every 5th time.'),
('Long-Pulley (low Row)', 'Back', 'Latissimus dorsi, Biceps brachii', '', 'https://wger.de/media/exercise-images/143/Cable-seated-rows-2.png', 'Sit down, put your feet on the supporting points and grab the bar with a wide grip. Pull the weight with a rapid movement towards your belly button, not upper. Keep your arms and elbows during the movement close to your body. Your shoulders are pulled together. Let the weight slowly down till your arms are completely stretched.'),
('Negative Crunches', 'Abs', 'Rectus abdominis', '', 'https://wger.de/media/exercise-images/93/Decline-crunch-1.png', 'Sit yourself on the decline bench and fix your legs. Cross your arms over the chest and bring with a rolling movement your upper body up, go now without a pause and with a slow movement down again. Don''t let your head move during the exercise.'),
('Preacher Curls', 'Arms', 'Brachialis, Brachialis', '', 'https://wger.de/media/exercise-images/193/Preacher-curl-3-1.png', ' Place the EZ curl bar on the rest handles in front of the preacher bench. Lean over the bench and grab the EZ curl bar with palms up. Sit down on the preacher bench seat so your upper arms rest on top of the pad and your chest is pressed against the pad. Lower the weight until your elbows are extended and arms are straight. Bring the weights back up to the starting point by contracting biceps. Repeat');
